/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Trade extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8548937118774339473L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Trade\",\"namespace\":\"com.example\",\"fields\":[{\"name\":\"tradeId\",\"type\":\"string\"},{\"name\":\"tradeType\",\"type\":\"string\"},{\"name\":\"price\",\"type\":{\"type\":\"record\",\"name\":\"Price\",\"fields\":[{\"name\":\"current\",\"type\":\"double\"},{\"name\":\"open\",\"type\":\"double\"},{\"name\":\"high\",\"type\":\"double\"},{\"name\":\"low\",\"type\":\"double\"},{\"name\":\"volume\",\"type\":\"double\"},{\"name\":\"close\",\"type\":\"double\"}]}},{\"name\":\"timestamp\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"Time\",\"fields\":[{\"name\":\"epochMillis\",\"type\":[\"null\",\"long\"],\"default\":null}]}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Trade> ENCODER =
      new BinaryMessageEncoder<Trade>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Trade> DECODER =
      new BinaryMessageDecoder<Trade>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Trade> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Trade> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Trade> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Trade>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Trade to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Trade from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Trade instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Trade fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence tradeId;
  private java.lang.CharSequence tradeType;
  private com.example.Price price;
  private com.example.Time timestamp;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Trade() {}

  /**
   * All-args constructor.
   * @param tradeId The new value for tradeId
   * @param tradeType The new value for tradeType
   * @param price The new value for price
   * @param timestamp The new value for timestamp
   */
  public Trade(java.lang.CharSequence tradeId, java.lang.CharSequence tradeType, com.example.Price price, com.example.Time timestamp) {
    this.tradeId = tradeId;
    this.tradeType = tradeType;
    this.price = price;
    this.timestamp = timestamp;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return tradeId;
    case 1: return tradeType;
    case 2: return price;
    case 3: return timestamp;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: tradeId = (java.lang.CharSequence)value$; break;
    case 1: tradeType = (java.lang.CharSequence)value$; break;
    case 2: price = (com.example.Price)value$; break;
    case 3: timestamp = (com.example.Time)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'tradeId' field.
   * @return The value of the 'tradeId' field.
   */
  public java.lang.CharSequence getTradeId() {
    return tradeId;
  }


  /**
   * Sets the value of the 'tradeId' field.
   * @param value the value to set.
   */
  public void setTradeId(java.lang.CharSequence value) {
    this.tradeId = value;
  }

  /**
   * Gets the value of the 'tradeType' field.
   * @return The value of the 'tradeType' field.
   */
  public java.lang.CharSequence getTradeType() {
    return tradeType;
  }


  /**
   * Sets the value of the 'tradeType' field.
   * @param value the value to set.
   */
  public void setTradeType(java.lang.CharSequence value) {
    this.tradeType = value;
  }

  /**
   * Gets the value of the 'price' field.
   * @return The value of the 'price' field.
   */
  public com.example.Price getPrice() {
    return price;
  }


  /**
   * Sets the value of the 'price' field.
   * @param value the value to set.
   */
  public void setPrice(com.example.Price value) {
    this.price = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public com.example.Time getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(com.example.Time value) {
    this.timestamp = value;
  }

  /**
   * Creates a new Trade RecordBuilder.
   * @return A new Trade RecordBuilder
   */
  public static com.example.Trade.Builder newBuilder() {
    return new com.example.Trade.Builder();
  }

  /**
   * Creates a new Trade RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Trade RecordBuilder
   */
  public static com.example.Trade.Builder newBuilder(com.example.Trade.Builder other) {
    if (other == null) {
      return new com.example.Trade.Builder();
    } else {
      return new com.example.Trade.Builder(other);
    }
  }

  /**
   * Creates a new Trade RecordBuilder by copying an existing Trade instance.
   * @param other The existing instance to copy.
   * @return A new Trade RecordBuilder
   */
  public static com.example.Trade.Builder newBuilder(com.example.Trade other) {
    if (other == null) {
      return new com.example.Trade.Builder();
    } else {
      return new com.example.Trade.Builder(other);
    }
  }

  /**
   * RecordBuilder for Trade instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Trade>
    implements org.apache.avro.data.RecordBuilder<Trade> {

    private java.lang.CharSequence tradeId;
    private java.lang.CharSequence tradeType;
    private com.example.Price price;
    private com.example.Price.Builder priceBuilder;
    private com.example.Time timestamp;
    private com.example.Time.Builder timestampBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.Trade.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.tradeId)) {
        this.tradeId = data().deepCopy(fields()[0].schema(), other.tradeId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.tradeType)) {
        this.tradeType = data().deepCopy(fields()[1].schema(), other.tradeType);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.price)) {
        this.price = data().deepCopy(fields()[2].schema(), other.price);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (other.hasPriceBuilder()) {
        this.priceBuilder = com.example.Price.newBuilder(other.getPriceBuilder());
      }
      if (isValidValue(fields()[3], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[3].schema(), other.timestamp);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (other.hasTimestampBuilder()) {
        this.timestampBuilder = com.example.Time.newBuilder(other.getTimestampBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing Trade instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.Trade other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.tradeId)) {
        this.tradeId = data().deepCopy(fields()[0].schema(), other.tradeId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.tradeType)) {
        this.tradeType = data().deepCopy(fields()[1].schema(), other.tradeType);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.price)) {
        this.price = data().deepCopy(fields()[2].schema(), other.price);
        fieldSetFlags()[2] = true;
      }
      this.priceBuilder = null;
      if (isValidValue(fields()[3], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[3].schema(), other.timestamp);
        fieldSetFlags()[3] = true;
      }
      this.timestampBuilder = null;
    }

    /**
      * Gets the value of the 'tradeId' field.
      * @return The value.
      */
    public java.lang.CharSequence getTradeId() {
      return tradeId;
    }


    /**
      * Sets the value of the 'tradeId' field.
      * @param value The value of 'tradeId'.
      * @return This builder.
      */
    public com.example.Trade.Builder setTradeId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.tradeId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'tradeId' field has been set.
      * @return True if the 'tradeId' field has been set, false otherwise.
      */
    public boolean hasTradeId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'tradeId' field.
      * @return This builder.
      */
    public com.example.Trade.Builder clearTradeId() {
      tradeId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'tradeType' field.
      * @return The value.
      */
    public java.lang.CharSequence getTradeType() {
      return tradeType;
    }


    /**
      * Sets the value of the 'tradeType' field.
      * @param value The value of 'tradeType'.
      * @return This builder.
      */
    public com.example.Trade.Builder setTradeType(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.tradeType = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'tradeType' field has been set.
      * @return True if the 'tradeType' field has been set, false otherwise.
      */
    public boolean hasTradeType() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'tradeType' field.
      * @return This builder.
      */
    public com.example.Trade.Builder clearTradeType() {
      tradeType = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'price' field.
      * @return The value.
      */
    public com.example.Price getPrice() {
      return price;
    }


    /**
      * Sets the value of the 'price' field.
      * @param value The value of 'price'.
      * @return This builder.
      */
    public com.example.Trade.Builder setPrice(com.example.Price value) {
      validate(fields()[2], value);
      this.priceBuilder = null;
      this.price = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'price' field has been set.
      * @return True if the 'price' field has been set, false otherwise.
      */
    public boolean hasPrice() {
      return fieldSetFlags()[2];
    }

    /**
     * Gets the Builder instance for the 'price' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.example.Price.Builder getPriceBuilder() {
      if (priceBuilder == null) {
        if (hasPrice()) {
          setPriceBuilder(com.example.Price.newBuilder(price));
        } else {
          setPriceBuilder(com.example.Price.newBuilder());
        }
      }
      return priceBuilder;
    }

    /**
     * Sets the Builder instance for the 'price' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.example.Trade.Builder setPriceBuilder(com.example.Price.Builder value) {
      clearPrice();
      priceBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'price' field has an active Builder instance
     * @return True if the 'price' field has an active Builder instance
     */
    public boolean hasPriceBuilder() {
      return priceBuilder != null;
    }

    /**
      * Clears the value of the 'price' field.
      * @return This builder.
      */
    public com.example.Trade.Builder clearPrice() {
      price = null;
      priceBuilder = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public com.example.Time getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public com.example.Trade.Builder setTimestamp(com.example.Time value) {
      validate(fields()[3], value);
      this.timestampBuilder = null;
      this.timestamp = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[3];
    }

    /**
     * Gets the Builder instance for the 'timestamp' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.example.Time.Builder getTimestampBuilder() {
      if (timestampBuilder == null) {
        if (hasTimestamp()) {
          setTimestampBuilder(com.example.Time.newBuilder(timestamp));
        } else {
          setTimestampBuilder(com.example.Time.newBuilder());
        }
      }
      return timestampBuilder;
    }

    /**
     * Sets the Builder instance for the 'timestamp' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.example.Trade.Builder setTimestampBuilder(com.example.Time.Builder value) {
      clearTimestamp();
      timestampBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'timestamp' field has an active Builder instance
     * @return True if the 'timestamp' field has an active Builder instance
     */
    public boolean hasTimestampBuilder() {
      return timestampBuilder != null;
    }

    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public com.example.Trade.Builder clearTimestamp() {
      timestamp = null;
      timestampBuilder = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Trade build() {
      try {
        Trade record = new Trade();
        record.tradeId = fieldSetFlags()[0] ? this.tradeId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.tradeType = fieldSetFlags()[1] ? this.tradeType : (java.lang.CharSequence) defaultValue(fields()[1]);
        if (priceBuilder != null) {
          try {
            record.price = this.priceBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("price"));
            throw e;
          }
        } else {
          record.price = fieldSetFlags()[2] ? this.price : (com.example.Price) defaultValue(fields()[2]);
        }
        if (timestampBuilder != null) {
          try {
            record.timestamp = this.timestampBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("timestamp"));
            throw e;
          }
        } else {
          record.timestamp = fieldSetFlags()[3] ? this.timestamp : (com.example.Time) defaultValue(fields()[3]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Trade>
    WRITER$ = (org.apache.avro.io.DatumWriter<Trade>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Trade>
    READER$ = (org.apache.avro.io.DatumReader<Trade>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.tradeId);

    out.writeString(this.tradeType);

    this.price.customEncode(out);

    if (this.timestamp == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      this.timestamp.customEncode(out);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.tradeId = in.readString(this.tradeId instanceof Utf8 ? (Utf8)this.tradeId : null);

      this.tradeType = in.readString(this.tradeType instanceof Utf8 ? (Utf8)this.tradeType : null);

      if (this.price == null) {
        this.price = new com.example.Price();
      }
      this.price.customDecode(in);

      if (in.readIndex() != 1) {
        in.readNull();
        this.timestamp = null;
      } else {
        if (this.timestamp == null) {
          this.timestamp = new com.example.Time();
        }
        this.timestamp.customDecode(in);
      }

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.tradeId = in.readString(this.tradeId instanceof Utf8 ? (Utf8)this.tradeId : null);
          break;

        case 1:
          this.tradeType = in.readString(this.tradeType instanceof Utf8 ? (Utf8)this.tradeType : null);
          break;

        case 2:
          if (this.price == null) {
            this.price = new com.example.Price();
          }
          this.price.customDecode(in);
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.timestamp = null;
          } else {
            if (this.timestamp == null) {
              this.timestamp = new com.example.Time();
            }
            this.timestamp.customDecode(in);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










